import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Hero from "../components/Hero/Hero";
import Navbar from "../components/Nav/NavBar";
import Card from "../components/ProjectsCards/Cards";
import SkillsGrid from "../components/SkillsGrid/SkillsGrid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />

        <Card />
        <Footer />
      </main>
    </div>
  );
}
